--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015-02-17 23:42:28
-- Server version: 5.5.41-0ubuntu0.14.04.1
-- Client version: 4.1
--



CREATE TABLE albania_chambers (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(30) NOT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 20
AVG_ROW_LENGTH = 41
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_chambers1 (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(30) NOT NULL,
  start_date varchar(30) DEFAULT NULL,
  end_date varchar(30) DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 20
AVG_ROW_LENGTH = 50
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_deputets (
  id int(11) NOT NULL AUTO_INCREMENT,
  albania_chamber_id int(11) NOT NULL,
  md5 char(32) NOT NULL,
  name varchar(255) DEFAULT NULL,
  paternity varchar(255) DEFAULT NULL,
  surname varchar(255) DEFAULT NULL,
  party varchar(255) DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 141
AVG_ROW_LENGTH = 102
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_docs (
  id int(11) NOT NULL AUTO_INCREMENT,
  albania_speeche_index_id int(11) NOT NULL,
  doc_md5 char(32) NOT NULL,
  doc_url text NOT NULL,
  content_al longtext DEFAULT NULL,
  content_en longtext DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  hints int(11) NOT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 167
AVG_ROW_LENGTH = 309514
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_logs (
  id int(11) NOT NULL AUTO_INCREMENT,
  type tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  logcontent text NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5699
AVG_ROW_LENGTH = 1461
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_mps_details (
  id int(11) NOT NULL AUTO_INCREMENT,
  url text DEFAULT NULL,
  name varchar(255) NOT NULL,
  md5 char(32) NOT NULL,
  post_data date DEFAULT NULL,
  image text NOT NULL,
  address text NOT NULL,
  email varchar(255) DEFAULT NULL,
  year_of_birth varchar(255) DEFAULT NULL,
  home_town text DEFAULT NULL,
  marital_status text DEFAULT NULL,
  education text DEFAULT NULL,
  professional_activity text DEFAULT NULL,
  political_activity text DEFAULT NULL,
  opting_in text DEFAULT NULL,
  group_parliamentary_committees text DEFAULT NULL,
  publishing text DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 17052
AVG_ROW_LENGTH = 1401
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_mps_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  url text NOT NULL,
  name text NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  active tinyint(4) NOT NULL DEFAULT 1,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX active (active),
  INDEX status (status),
  INDEX status_2 (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 112
AVG_ROW_LENGTH = 103
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_pdfs (
  id int(11) NOT NULL AUTO_INCREMENT,
  albania_vote_index_id int(11) NOT NULL,
  pdf_md5 char(32) NOT NULL,
  pdf_url text NOT NULL,
  content_sr longtext DEFAULT NULL,
  content_en longtext DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_speeche_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  post_date date DEFAULT NULL,
  url text NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  active tinyint(4) NOT NULL DEFAULT 1,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX active (active),
  INDEX post_date (post_date),
  INDEX status (status),
  INDEX status_2 (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 167
AVG_ROW_LENGTH = 92
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE albania_vote_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  post_date date DEFAULT NULL,
  name text NOT NULL,
  url text NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  active tinyint(4) NOT NULL DEFAULT 1,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX active (active),
  INDEX post_date (post_date),
  INDEX status (status),
  INDEX status_2 (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 101
AVG_ROW_LENGTH = 310
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_committe_funcs (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_committee_id int(11) NOT NULL,
  kosovo_mps_detail_id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 94118
AVG_ROW_LENGTH = 48
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_committees (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name text DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 19
AVG_ROW_LENGTH = 108
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_committees_kosovo_mps_details (
  kosovo_mps_detail_id int(11) NOT NULL,
  kosovo_committee_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_logs (
  id int(11) NOT NULL AUTO_INCREMENT,
  type tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  logcontent text NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 14111
AVG_ROW_LENGTH = 387
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_activities (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_detail_id int(11) NOT NULL,
  name text DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1046
AVG_ROW_LENGTH = 101
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_addresses (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_detail_id int(11) NOT NULL,
  name text DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 147
AVG_ROW_LENGTH = 55
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_details (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_index_id int(11) NOT NULL,
  name varchar(255) NOT NULL,
  md5 char(32) NOT NULL,
  image text DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 8563
AVG_ROW_LENGTH = 139
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_details_kosovo_parliamentary_groups (
  kosovo_parliamentary_group_id int(11) NOT NULL,
  kosovo_mps_detail_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_details_kosovo_parties (
  kosovo_party_id int(11) NOT NULL,
  kosovo_mps_detail_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_educations (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_detail_id int(11) NOT NULL,
  name text DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 444
AVG_ROW_LENGTH = 85
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_menu_id int(11) NOT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  url text DEFAULT NULL,
  name text DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1531
AVG_ROW_LENGTH = 83
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_languages (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_detail_id int(11) NOT NULL,
  name text DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 96
AVG_ROW_LENGTH = 53
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_menus (
  id int(11) NOT NULL AUTO_INCREMENT,
  url text DEFAULT NULL,
  name text DEFAULT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 83
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_mps_personal_data (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_mps_detail_id int(11) NOT NULL,
  name text DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 308
AVG_ROW_LENGTH = 66
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_parliamentary_groups (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 42
AVG_ROW_LENGTH = 70
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_parties (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  shortcut varchar(30) DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 37
AVG_ROW_LENGTH = 68
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_pdfs (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_speeche_content_id int(11) NOT NULL,
  pdf_md5 char(32) NOT NULL,
  pdf_url text NOT NULL,
  content_sr longtext DEFAULT NULL,
  content_en longtext DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 545
AVG_ROW_LENGTH = 135941
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_speeche_contents (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_speeche_index_id int(11) NOT NULL DEFAULT 0,
  title text NOT NULL,
  post_date varchar(255) NOT NULL,
  intro text DEFAULT NULL,
  content_md5 char(32) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5752
AVG_ROW_LENGTH = 699
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_speeche_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  post_uid int(11) UNSIGNED DEFAULT NULL,
  post_date datetime DEFAULT NULL,
  post_group_title text DEFAULT NULL,
  url text NOT NULL,
  index_md5 char(32) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  active tinyint(4) NOT NULL DEFAULT 1,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX active (active),
  INDEX post_date (post_date),
  INDEX status (status),
  INDEX status_2 (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 5752
AVG_ROW_LENGTH = 109
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE kosovo_txts (
  id int(11) NOT NULL AUTO_INCREMENT,
  kosovo_speeche_content_id int(11) NOT NULL,
  txt_md5 char(32) NOT NULL,
  txt_url text NOT NULL,
  content_sr longtext DEFAULT NULL,
  content_en longtext DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 951
AVG_ROW_LENGTH = 2877
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE quele_to_sends (
  id int(11) NOT NULL AUTO_INCREMENT,
  direct varchar(255) NOT NULL,
  uid varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  data text DEFAULT NULL,
  md5 char(32) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  code int(11) DEFAULT 0,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX direct (direct),
  INDEX hints (hints),
  INDEX md5 (md5),
  INDEX modified (modified),
  INDEX status (status),
  INDEX type (type),
  INDEX uid (uid)
)
ENGINE = MYISAM
AUTO_INCREMENT = 156692
AVG_ROW_LENGTH = 854
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE schedules (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  task varchar(255) NOT NULL,
  `interval` int(11) NOT NULL DEFAULT 10,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 32
AVG_ROW_LENGTH = 66
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_committe_funcs (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_committe_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 491
AVG_ROW_LENGTH = 62
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_committes (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name text DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 21
AVG_ROW_LENGTH = 215
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_committes_serbian_mps_details (
  serbian_mps_detail_id int(11) NOT NULL,
  serbian_committe_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_delegates (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_menu_data_id int(11) UNSIGNED NOT NULL,
  `terminated` tinyint(4) NOT NULL DEFAULT 0,
  api_uid varchar(255) DEFAULT NULL,
  url_uid int(11) UNSIGNED DEFAULT NULL,
  url text DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  parlamentary_group varchar(255) DEFAULT NULL,
  party varchar(255) DEFAULT NULL,
  start_date date DEFAULT NULL,
  end_date date DEFAULT NULL,
  hometown varchar(255) DEFAULT NULL,
  age varchar(10) DEFAULT NULL,
  type varchar(30) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1378
AVG_ROW_LENGTH = 161
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_delegation_membership_funcs (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_delegation_membership_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 113
AVG_ROW_LENGTH = 70
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_delegation_memberships (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name text DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 226
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_delegation_memberships_serbian_mps_details (
  serbian_mps_detail_id int(11) NOT NULL,
  serbian_delegation_membership_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_friendship_funcs (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_friendship_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 109
AVG_ROW_LENGTH = 90
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_friendships (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name text DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 75
AVG_ROW_LENGTH = 240
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_friendships_serbian_mps_details (
  serbian_mps_detail_id int(11) NOT NULL,
  serbian_friendship_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_functions (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name text DEFAULT NULL,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 106
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_functions_serbian_mps_details (
  serbian_mps_detail_id int(11) NOT NULL,
  serbian_function_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_logs (
  id int(11) NOT NULL AUTO_INCREMENT,
  type tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  logcontent text NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 13877
AVG_ROW_LENGTH = 245
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_menu_data (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  start_date date DEFAULT NULL,
  url text NOT NULL,
  menu_md5 char(32) NOT NULL,
  table_md5 char(32) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 2193
AVG_ROW_LENGTH = 281
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_mps_details (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_menu_data_id int(11) NOT NULL DEFAULT 0,
  en_name varchar(255) DEFAULT NULL,
  name varchar(255) NOT NULL,
  md5 char(32) NOT NULL,
  image text NOT NULL,
  year_of_birth varchar(255) DEFAULT NULL,
  occupation varchar(255) DEFAULT NULL,
  electoral_list text DEFAULT NULL,
  verification_mandate varchar(255) DEFAULT NULL,
  biography text DEFAULT NULL,
  www varchar(255) DEFAULT NULL,
  facebook varchar(255) DEFAULT NULL,
  twitter varchar(255) DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  hints int(11) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 887
AVG_ROW_LENGTH = 575
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_mps_details_serbian_parliamentary_groups (
  serbian_parliamentary_group_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_mps_details_serbian_parties (
  serbian_party_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_mps_details_serbian_residences (
  serbian_residence_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 9
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_parliamentary_group_funcs (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_parliamentary_group_id int(11) NOT NULL,
  serbian_mps_detail_id int(11) NOT NULL,
  name varchar(255) DEFAULT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 36
AVG_ROW_LENGTH = 64
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_parliamentary_groups (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  url text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 230
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_parties (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  shortcut varchar(30) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  www varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  image text DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  fax varchar(255) DEFAULT NULL,
  phone_fax varchar(255) DEFAULT NULL,
  sources text DEFAULT NULL,
  api tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 26
AVG_ROW_LENGTH = 477
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_pdfs (
  id int(11) NOT NULL AUTO_INCREMENT,
  pdf_md5 char(32) NOT NULL,
  post_date date DEFAULT NULL,
  stamp_in_text varchar(30) NOT NULL,
  pdf_url text NOT NULL,
  name_sr text DEFAULT NULL,
  name_en text DEFAULT NULL,
  content_sr longtext DEFAULT NULL,
  content_en longtext DEFAULT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 614
AVG_ROW_LENGTH = 16395
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_residences (
  id int(11) NOT NULL AUTO_INCREMENT,
  uid int(11) DEFAULT NULL,
  name varchar(255) NOT NULL,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 225
AVG_ROW_LENGTH = 49
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_speeche_contents (
  id int(11) NOT NULL AUTO_INCREMENT,
  serbian_speeche_index_id int(11) NOT NULL DEFAULT 0,
  title text NOT NULL,
  post_date varchar(255) NOT NULL,
  convert_date date NOT NULL,
  intro text DEFAULT NULL,
  image text DEFAULT NULL,
  caption text DEFAULT NULL,
  content_md5 char(32) NOT NULL,
  content longtext NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX content_md5 (content_md5),
  INDEX convert_date (convert_date),
  INDEX post_date (post_date),
  INDEX status (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 561
AVG_ROW_LENGTH = 12399
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE serbian_speeche_indices (
  id int(11) NOT NULL AUTO_INCREMENT,
  post_uid int(11) UNSIGNED DEFAULT NULL,
  lang char(2) NOT NULL,
  lay_uid int(11) UNSIGNED DEFAULT NULL,
  post_date date DEFAULT NULL,
  post_group_title text DEFAULT NULL,
  url text NOT NULL,
  index_md5 char(32) NOT NULL,
  status tinyint(4) NOT NULL DEFAULT 0,
  active tinyint(4) NOT NULL DEFAULT 1,
  created datetime NOT NULL,
  modified datetime NOT NULL,
  PRIMARY KEY (id),
  INDEX active (active),
  INDEX post_date (post_date),
  INDEX status (status),
  INDEX status_2 (status)
)
ENGINE = MYISAM
AUTO_INCREMENT = 562
AVG_ROW_LENGTH = 275
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE users (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  password varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  role varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  created datetime DEFAULT NULL,
  modified datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 92
CHARACTER SET utf8
COLLATE utf8_general_ci;
